export function randomHurryUpQuip(){
    return randomItem(hurryUpQuips)
}

export function randomNoSelectionQuip(){
    return randomItem(noSelectionsQuips)
}

function randomItem(array: any){
    const randomIndex = Math.floor(array.length * Math.random());
    return array[randomIndex];
}

export const hurryUpQuips = [
    "Crichets...",
    "Can you guys hurry up?",
    "I knit a sweater while you guys were talking",
    "So... Bored...",
    "I’m not getting any younger here. Make a choice.",
    "Do you need a minute...or an hour?",
    "Oh, take your time. It’s not like deadlines exist.",
    "Are you brainstorming or napping? Hurry up!",
    "The suspense is killing me. Pick already!",
    "This is called *pointing poker,* not *pointless staring.*",
    "Some of us have lives to get back to. Just saying.",
    "I’d offer you a coffee break, but you’ve taken one already.",
    "Should I send a search party for your decision?",
    "The paint on the wall is drying faster than you.",
    "We all believe in you—kind of.",
    "At this rate, we’ll finish by the next fiscal year.",
    "What’s the holdup? It’s just a number.",
    "Would a bribe help speed things up?",
    "Analysis paralysis is a thing. Snap out of it.",
    "I'm not mad, just disappointed.",
    "You know this isn’t quantum physics, right?",
    "Your boss called. They said, 'Hurry up!'",
    "We’re edging into glacial speeds here.",
    "Take your time. The sun won’t set for another...oh wait, it just did.",
    "I hope you weren’t planning to grow old deciding this.",
    "What’s slower than a sloth? You. Right now.",
    "Blink twice if you’re still alive.",
    "I’ve seen turtles make decisions faster.",
    "Oh, so this is how eternity feels.",
    "No pressure, but literally everyone is waiting on you.",
    "Are you consulting a higher power or just stalling?",
    "Did you forget how numbers work?",
    "Would you like an abacus? Might help.",
    "Don’t make me start playing elevator music.",
    "This isn’t a museum—stop admiring the cards.",
    "Is this your first time making a decision?",
    "If thinking were an Olympic sport, you’d still lose for slowness.",
    "Fun fact: This app moves faster than you do.",
    "Is this a strategy or procrastination?",
    "We could’ve finished five projects by now.",
    "Should I come back later? Like...next year?",
    "I’m updating your profile to ‘Certified Deliberator.’",
    "I’d applaud your effort, but I’m falling asleep.",
    "Even your internet connection is faster than this.",
    "Have you tried flipping a coin? Might be faster.",
    "Don’t worry; we’ll hold your retirement party here.",
    "Indecision is a decision. Just not a good one.",
    "This is a *timed* game. Just FYI.",
    "Hesitation is the cousin of failure. Move it!",
    "The dinosaurs made decisions faster than this.",
    "This app doesn’t charge by the hour. Lucky for you.",
    "Thinking too long is a rookie move.",
    "Do we need to order lunch? Dinner? Breakfast?",
    "I’d suggest you sleep on it, but you’ve done enough of that already.",
    "Time flies. Too bad you don’t.",
    "I admire your patience—with yourself.",
    "Are you secretly coding the next feature? Because that’s the only excuse.",
    "Did you lose your decision-making privileges?",
    "Hurry up before your computer battery dies.",
    "Is it really that hard to pick a card? Really?",
    "At this point, we’ll need a documentary about your decision-making process.",
    "You do realize there’s no wrong answer, right?",
    "Maybe we should rename this app *Decision Delayer* instead.",
    "How do you function in a drive-thru?",
    "Do you need me to call a lifeline for you?",
    "Blink if you’ve got an idea.",
    "You’re testing my patience, and I was programmed to have infinite amounts.",
    "One small step for you, one giant leap for our productivity.",
    "If decisions were this slow in nature, evolution would’ve given up.",
    "You’re making the snail look bad.",
    "Have you considered speed dating for decisions?",
    "I bet you’re *great* at staring contests.",
    "It’s called *pointing poker,* not *pondering poker.*",
    "The progress bar is ashamed of you.",
    "Should I send you a decision flowchart?",
    "Oh, I see. You’re going for the ‘World’s Slowest Click’ record.",
    "Fun fact: The average human makes 35,000 decisions a day. You’re at 1.",
    "Don’t hurt yourself overthinking.",
    "Remember: It’s just pointing, not planning the moon landing.",
    "Every second you wait, a poor server sheds a digital tear.",
    "Are you meditating or gaming? Hard to tell.",
    "You’re moving slower than dial-up internet.",
    "If this was chess, your clock would’ve run out.",
    "Should I come back when you’re ready to commit?",
    "In case you forgot, other people are waiting on you.",
    "This app doesn’t have a ‘pause life’ feature.",
    "I can see why they call it *work*. You’re allergic to it.",
    "Would you like to consult an oracle first?",
    "It’s not rocket science, but it’s starting to feel like it.",
    "Do you have decision-making fatigue already?",
    "You’re procrastinating so hard it’s almost art.",
    "This is why meetings run long.",
    "Do you need a tutorial on how to tap a card?",
    "You’re setting a new low for productivity.",
    "I’ve seen glaciers with more urgency.",
    "We’d make faster progress if you played with a sundial.",
    "Tick-tock, my friend. Tick-tock.",
    "You’re moving slower than my grandma's dial-up connection.",
    "This is why nobody trusts committees.",
    "Are you philosophizing or gaming? Hard to tell.",
    "The only thing slower than your decision-making is a Windows update.",
    "At this rate, I might need an update before you’re done.",
    "If hesitation were a skill, you’d be a black belt.",
    "You know what they say: the first decision is usually the best one. Try it."
  ]

    const noSelectionsQuips = [
    "Hello? Is anybody out there? Or is this just a meeting mirage?",
    "The cards are feeling lonely... pick something already!",
    "It’s like waiting for a plot twist that never comes.",
    "Silence speaks volumes, but not about story points.",
    "You miss 100% of the points you don’t pick.",
    "No rush, it’s not like the sprint is ending soon... oh wait.",
    "Procrastination: the ultimate poker strategy.",
    "Everyone’s still calculating Fibonacci, right?",
    "If pointing poker were a staring contest, you’d all win.",
    "At this rate, we’ll release the next update in 2035.",
    "Did someone say ‘unanimous indecision’?!",
    "The suspense is killing me... or is that just the coffee talking?",
    "Fun fact: Story points don’t assign themselves.",
    "Plot twist: the cards are waiting on *you*.",
    "Teamwork makes the dream work—anytime now!",
    "No votes? Bold strategy. Let’s see if it pays off.",
    "Who needs estimates when you’ve got vibes, right?",
    "This is fine. We’ll just wing it in production.",
    "Friendly reminder: Time’s a-tickin’, and deadlines don’t wait.",
    "If hesitation were a story point, this would be a 13.",
    "Are you all secretly playing ‘the quiet game’?",
    "We’re not here to build suspense, folks.",
    "Can someone break the ice before we all freeze?",
    "It’s poker, not a staring contest. Make a move!",
    "Imagine how fast this sprint would go if we all picked.",
    "Raise your hand if you forgot how this works.",
    "Your cards are safe to touch. Promise.",
    "Shhh... the story points are meditating.",
    "Waiting for input... and waiting... and waiting...",
    "Is this an Agile meeting or a mime performance?",
    "Any second now, the estimates will estimate themselves.",
    "This isn’t a trick question, you know.",
    "Blink twice if you’re confused.",
    "Do I need to bribe you with coffee?",
    "Story points called. They’d like to be chosen, please.",
    "Let’s not turn this into a Netflix binge-worthy wait.",
    "If thinking hard were a story point, you’d all be 21.",
    "Should we start the meeting over from the top?",
    "Is this the dramatic pause before the big reveal?",
    "You’re making this more mysterious than it needs to be.",
    "Pick a card, any card! No magic involved.",
    "The cards are digital, but your hesitation feels real.",
    "There’s no wrong answer... except not picking one.",
    "Can we wrap this up before AI estimates the sprint for us?",
    "Every second of silence adds a story point.",
    "Should we vote on voting?",
    "The universe isn’t going to align those cards for you.",
    "It’s poker, not rocket science. Tap a number.",
    "This app does more than just sit there, you know.",
    "Story points: still waiting to be adopted.",
    "Is this what Agile purgatory feels like?",
    "Breaking news: no one has selected anything yet.",
    "Fun fact: This meeting could have been an email.",
    "Has the concept of numbers suddenly become confusing?",
    "The team that doesn’t point together... sits forever.",
    "The cards are patient, but I’m not.",
    "No pressure, but the clock is judging you.",
    "I didn’t realize ‘indecision’ was part of the backlog.",
    "The user stories are writing themselves in the background.",
    "Fun game: Guess how long this will take without estimates.",
    "Are we silently protesting the use of story points?",
    "This isn’t Jeopardy; you don’t need to buzz in.",
    "The sprint ends when you decide it ends.",
    "Imagine how productive we’d be if we all picked a number.",
    "Quick question: Is this a dramatic pause or a freeze frame?",
    "We could have released the feature by now.",
    "You’re making Agile feel like a glacier.",
    "The cards are digital, but this wait feels analog.",
    "Don’t overthink it—it’s just a number.",
    "If you don’t pick soon, I’ll assign 99 to everything.",
    "The backlog is watching you. Judging silently.",
    "Fun fact: Sprint planning doesn’t have a halftime show.",
    "Are we waiting for divine intervention to assign points?",
    "Please select something before my battery dies.",
    "You’ve entered the zone of infinite indecision.",
    "If we had a dollar for every second of silence, we’d fund the sprint.",
    "Tap a number! It’s easier than texting.",
    "Fun fact: Hesitation isn’t an Agile value.",
    "The cards are sad, and it’s your fault.",
    "Should we play actual poker while we wait?",
    "Your cards are waiting. Your PM is too.",
    "At this rate, we’ll be estimating during the retrospective.",
    "Did someone forget we’re in a meeting?",
    "I didn’t realize this was a meditative session.",
    "Even the Fibonacci sequence didn’t take this long.",
    "You know, Agile is supposed to be fast, right?",
    "Is this part of the sprint or the sprint planning afterparty?",
    "I’ll start assigning random numbers soon. Don’t test me.",
    "The cards won’t bite. Probably.",
    "Should I play elevator music while you decide?",
    "We’re not launching rockets; just pick a number.",
    "The cards can’t do this alone.",
    "If this were a race, we’d still be at the starting line.",
    "Can we finish before my coffee gets cold?",
    "You’re redefining the art of suspense.",
    "It’s story points, not quantum physics.",
    "Someone throw the first card so we can all move on."
  ]