export function randomQuip(){
    const randomIndex = Math.floor(quips.length * Math.random());
    //console.log(randomIndex)
    return quips[randomIndex];
}

export const quips = [
    "Crichets...",
    "Can you guys hurry up?",
    "I knit a sweater while you guys were talking",
    "So... Bored...",
    "I’m not getting any younger here. Make a choice.",
    "Do you need a minute...or an hour?",
    "Oh, take your time. It’s not like deadlines exist.",
    "Are you brainstorming or napping? Hurry up!",
    "The suspense is killing me. Pick already!",
    "This is called *pointing poker,* not *pointless staring.*",
    "Some of us have lives to get back to. Just saying.",
    "I’d offer you a coffee break, but you’ve taken one already.",
    "Should I send a search party for your decision?",
    "The paint on the wall is drying faster than you.",
    "We all believe in you—kind of.",
    "At this rate, we’ll finish by the next fiscal year.",
    "What’s the holdup? It’s just a number.",
    "Would a bribe help speed things up?",
    "Analysis paralysis is a thing. Snap out of it.",
    "I'm not mad, just disappointed.",
    "You know this isn’t quantum physics, right?",
    "Your boss called. They said, 'Hurry up!'",
    "We’re edging into glacial speeds here.",
    "Take your time. The sun won’t set for another...oh wait, it just did.",
    "I hope you weren’t planning to grow old deciding this.",
    "What’s slower than a sloth? You. Right now.",
    "Blink twice if you’re still alive.",
    "I’ve seen turtles make decisions faster.",
    "Oh, so this is how eternity feels.",
    "No pressure, but literally everyone is waiting on you.",
    "Are you consulting a higher power or just stalling?",
    "Did you forget how numbers work?",
    "Would you like an abacus? Might help.",
    "Don’t make me start playing elevator music.",
    "This isn’t a museum—stop admiring the cards.",
    "Is this your first time making a decision?",
    "If thinking were an Olympic sport, you’d still lose for slowness.",
    "Fun fact: This app moves faster than you do.",
    "Is this a strategy or procrastination?",
    "We could’ve finished five projects by now.",
    "Should I come back later? Like...next year?",
    "I’m updating your profile to ‘Certified Deliberator.’",
    "I’d applaud your effort, but I’m falling asleep.",
    "Even your internet connection is faster than this.",
    "Have you tried flipping a coin? Might be faster.",
    "Don’t worry; we’ll hold your retirement party here.",
    "Indecision is a decision. Just not a good one.",
    "This is a *timed* game. Just FYI.",
    "Hesitation is the cousin of failure. Move it!",
    "The dinosaurs made decisions faster than this.",
    "This app doesn’t charge by the hour. Lucky for you.",
    "Thinking too long is a rookie move.",
    "Do we need to order lunch? Dinner? Breakfast?",
    "I’d suggest you sleep on it, but you’ve done enough of that already.",
    "Time flies. Too bad you don’t.",
    "I admire your patience—with yourself.",
    "Are you secretly coding the next feature? Because that’s the only excuse.",
    "Did you lose your decision-making privileges?",
    "Hurry up before your computer battery dies.",
    "Is it really that hard to pick a card? Really?",
    "At this point, we’ll need a documentary about your decision-making process.",
    "You do realize there’s no wrong answer, right?",
    "Maybe we should rename this app *Decision Delayer* instead.",
    "How do you function in a drive-thru?",
    "Do you need me to call a lifeline for you?",
    "Blink if you’ve got an idea.",
    "You’re testing my patience, and I was programmed to have infinite amounts.",
    "One small step for you, one giant leap for our productivity.",
    "If decisions were this slow in nature, evolution would’ve given up.",
    "You’re making the snail look bad.",
    "Have you considered speed dating for decisions?",
    "I bet you’re *great* at staring contests.",
    "It’s called *pointing poker,* not *pondering poker.*",
    "The progress bar is ashamed of you.",
    "Should I send you a decision flowchart?",
    "Oh, I see. You’re going for the ‘World’s Slowest Click’ record.",
    "Fun fact: The average human makes 35,000 decisions a day. You’re at 1.",
    "Don’t hurt yourself overthinking.",
    "Remember: It’s just pointing, not planning the moon landing.",
    "Every second you wait, a poor server sheds a digital tear.",
    "Are you meditating or gaming? Hard to tell.",
    "You’re moving slower than dial-up internet.",
    "If this was chess, your clock would’ve run out.",
    "Should I come back when you’re ready to commit?",
    "In case you forgot, other people are waiting on you.",
    "This app doesn’t have a ‘pause life’ feature.",
    "I can see why they call it *work*. You’re allergic to it.",
    "Would you like to consult an oracle first?",
    "It’s not rocket science, but it’s starting to feel like it.",
    "Do you have decision-making fatigue already?",
    "You’re procrastinating so hard it’s almost art.",
    "This is why meetings run long.",
    "Do you need a tutorial on how to tap a card?",
    "You’re setting a new low for productivity.",
    "I’ve seen glaciers with more urgency.",
    "We’d make faster progress if you played with a sundial.",
    "Tick-tock, my friend. Tick-tock.",
    "You’re moving slower than my grandma's dial-up connection.",
    "This is why nobody trusts committees.",
    "Are you philosophizing or gaming? Hard to tell.",
    "The only thing slower than your decision-making is a Windows update.",
    "At this rate, I might need an update before you’re done.",
    "If hesitation were a skill, you’d be a black belt.",
    "You know what they say: the first decision is usually the best one. Try it."
  ]